### ISSUE TITLE
 Failed to copy the sharded table; 'Did not find a suitable index' and exception.

### ISSUE THREAD

**Issue by MarijnStevens** [Azure/elastic-db-tools#141]
We trying to move shardlets from one to another, but the split-merge tool returns a FOREIGN KEY constraint conflict exception; after an '_Did not find a suitable index to enable divison of a batch into smaller groups for data movement._' warning/error.

How is the order determent of the split-merge tool ? Because it looks like it should first do the Companies table. 

Any clue what is going on ? 
**Tables:** 

```
-- Note that CreationUser_Ref is not a FOREIGN KEY. 
-- ParentCompany_Ref can be NULL or point to the Companies table. 
CREATE TABLE [dbo].[Companies](
	[Id] [uniqueidentifier] NOT NULL,
	[Branding_Ref] [uniqueidentifier] NULL,
	[CreationUser_Ref] [uniqueidentifier] NOT NULL,
	[ParentCompany_Ref] [uniqueidentifier] NULL,
        ... 
	[Description] [dbo].[description] NOT NULL,
	[CompanyType] [tinyint] NOT NULL,
	[MaxUsers] [int] NOT NULL,
	[ShardingKey] [int] NOT NULL,
 CONSTRAINT [PK_Companies] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

ALTER TABLE [dbo].[Companies]  WITH CHECK ADD  CONSTRAINT [FK_Companies_Branding] FOREIGN KEY([Branding_Ref])
REFERENCES [dbo].[Brandings] ([Id])
GO

ALTER TABLE [dbo].[Companies] CHECK CONSTRAINT [FK_Companies_Branding]
GO

CREATE TABLE [dbo].[CompanyGroups](
	[Id] [uniqueidentifier] NOT NULL,
	[Company_Ref] [uniqueidentifier] NOT NULL,
	[User_Ref] [uniqueidentifier] NULL,
	[Parent_Ref] [uniqueidentifier] NULL,
	[CreationUser_Ref] [uniqueidentifier] NOT NULL,
        ...
	[CreationTimestamp] [datetime] NOT NULL,
	[Description] [dbo].[description] NOT NULL,
	[CreationUser_Ref] [uniqueidentifier] NOT NULL,
	[ShardingKey] [int] NOT NULL,
 CONSTRAINT [PK_CompanyGroups] PRIMARY KEY NONCLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
)

GO

ALTER TABLE [dbo].[CompanyGroups]  WITH CHECK ADD  CONSTRAINT [FK_CompanyGroups_Company] FOREIGN KEY([Company_Ref])
REFERENCES [dbo].[Companies] ([Id])
GO

ALTER TABLE [dbo].[CompanyGroups] CHECK CONSTRAINT [FK_CompanyGroups_Company]
GO

ALTER TABLE [dbo].[CompanyGroups]  WITH CHECK ADD  CONSTRAINT [FK_CompanyGroups_User] FOREIGN KEY([User_Ref])
REFERENCES [dbo].[Users] ([Id])
GO

ALTER TABLE [dbo].[CompanyGroups] CHECK CONSTRAINT [FK_CompanyGroups_User]
GO

```

**Operation Log:**

[Informational] Operation has been queued.
[Informational] Starting Split-Merge state machine for request.
[Informational] Performing data consistency checks on target shards.
[Informational] Successfully copied reference table [dbo].[Brandings].
[Informational] Successfully copied reference table [dbo].[AnalyticsModules].
[Informational] Successfully copied reference table [dbo].[AnalyticsSubscriptions].
[Informational] Successfully copied reference table [dbo].[AnalyticsSubscriptionModules].
[Informational] Successfully copied reference table [dbo].[AnalyticsSubscriptionDealerTiers].
[Informational] Successfully copied reference table [dbo].[ApplicationVersions].
[Informational] Successfully copied reference table [dbo].[BlacklistedControllers].
[Informational] Successfully copied reference table [dbo].[ControllerServers].
[Informational] Successfully copied reference table [dbo].[Geolocations].
[Informational] Successfully copied reference table [dbo].[ControllerServerStatistics].
[Informational] Successfully copied reference table [dbo].[DealerSubscriptionTypes].
[Informational] Successfully copied reference table [dbo].[DeviceTypes].
[Informational] Successfully copied reference table [dbo].[SystemSubscriptions].
[Informational] Successfully copied reference table [dbo].[DeviceSubscriptions].
[Informational] Successfully copied reference table [dbo].[News].
[Informational] Successfully copied reference table [dbo].[TableStatistics].
[Informational] Moving key range [33:34) of sharded tables.
[Informational] Successfully copied key range [33:34) for sharded table [dbo].[Storage].
[Error] Failed to copy the sharded table '[dbo].[CompanyGroups]' for the range [33:34).
Details:
[Informational] Did not find a suitable index to enable divison of a batch into smaller groups for data movement.
[Error] System.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_CompanyGroups_Company". The conflict occurred in database "ControllerDB-Sohosted23052016-shard2", table "dbo.Companies", column 'Id'.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlBulkCopy.RunParser(BulkCopySimpleResultSet bulkCopyHandler)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinuedOnSuccess(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at Microsoft.Azure.SqlDatabase.ElasticScale.SplitMerge.Worker.Utilities.SqlAssistant.<>c__DisplayClass3.<BulkCopy>b__2() in d:\_Bld\8089\4133\Sources\Src\ShardSplitMerge\FsmWorkerRole\Utils\SqlAssistant.cs:line 245
   at Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.RetryPolicy.<>c__DisplayClass1.<ExecuteAction>b__0()
   at Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Microsoft.Azure.SqlDatabase.ElasticScale.SplitMerge.Worker.StateMachines.BulkCopyStateMachine.<TransitionBulkCopyingTableDataNoChunking>b__f() in d:\_Bld\8089\4133\Sources\Src\ShardSplitMerge\FsmWorkerRole\StateMachines\BulkCopyStateMachine.cs:line 1060
   at Microsoft.Azure.SqlDatabase.ElasticScale.SplitMerge.Worker.Utilities.ExecuteAction.ExecuteFsmAction(String stateName, String actionName, Func`1 fsmAction, Func`2 errorAction) in d:\_Bld\8089\4133\Sources\Src\ShardSplitMerge\FsmWorkerRole\Utils\ExecuteAction.cs:line 60
ClientConnectionId:0994eaf8-f3da-443d-9799-1f22e0dfc745
Error Number:547,State:0,Class:16
ClientConnectionId before routing:b1850845-f1ca-4296-999f-85406a68bc0d
Routing Destination:e79b1cb426dd.tr22.westeurope1-a.worker.database.windows.net,11014

[Informational] Cleaning up source and target shards following a failure or cancellation requested by user.

**Comment by MarijnStevens** [comment]
I've closed the issue. The problem seems to be related to the nature of our database schema, (recursive tables for one). So the problem is that the order executed is important, and the split-merge tool as is; is very restrictive in what it does, when it decide to do it, and except for the RequestStatus, no clue what it is doing at any moment. We decided we need a more versatile service.

**Comment by jaredmoo** [comment]
Hi,

Sorry we didn't get a chance to look at this yet. The error that I see is this one. So my understanding is that `CompanyGroups` has a foreign key on `Companies`. Are both of these tables sharded (i.e. different rows on different shards), or is one of them a reference table (i.e. same rows on all shards)?

Split-Merge does have logic to follow foreign keys and copy tables in the correct order, but it doesn't handle reference cycles since it doesn't know which table to copy first.

`[Error] System.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_CompanyGroups_Company". The conflict occurred in database "ControllerDB-Sohosted23052016-shard2", table "dbo.Companies", column 'Id'.`

Cheers,
Jared
