### ISSUE TITLE
MarkMappingOffline hangs until timeout

### ISSUE THREAD

**Issue by chrsitab** [Azure/elastic-db-tools#166]
In version 1.3.3 MarkMappingOffline just hangs until timeout exception occurs. When downgrading to 1.3.2 it works as expected.

Here is a stacktrace dump:
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperation.Do()
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.BaseShardMapper.Update[TMapping,TUpdate,TStatus](TMapping currentMapping, TUpdate update, Func`4 constructMapping, Func`2 statusAsInt, Func`2 intAsStatus, Guid lockOwnerId)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ListShardMapper`1.Update(PointMapping`1 currentMapping, PointMappingUpdate update, Guid lockOwnerId)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.BaseShardMapper.SetStatus[TMapping,TUpdate,TStatus](TMapping mapping, TStatus status, Func`2 getStatus, Func`2 createUpdate, Func`4 runUpdate, Guid lockOwnerId)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ListShardMapper`1.MarkMappingOffline(PointMapping`1 mapping, Guid lockOwnerId)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ListShardMap`1.MarkMappingOffline(PointMapping`1 mapping)

**Comment by ms92ita** [comment]
I've encountered the same issue and i have resolved with the downgrade of version. But in my case I needed version 1.3.0 to resolve the timeout.
With the version 2.0.0 on preview, I've encountered a Null Reference Exception in MarkMappingOffline with this stacktrace:

`in Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperationFactory.CreateUpdateMappingOperation(StoreOperationCode operationCode, ShardMapManager shardMapManager, Guid operationId, StoreOperationState undoStartState, XElement root, Guid originalShardVersionRemoves, Guid originalShardVersionAdds)
   in Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperationFactory.FromLogEntry(ShardMapManager shardMapManager, IStoreLogEntry so)
   in Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperation.Do()
   in Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.BaseShardMapper.Update[TMapping,TUpdate,TStatus](TMapping currentMapping, TUpdate update, Func'4 constructMapping, Func'2 statusAsInt, Func'2 intAsStatus, Guid lockOwnerId, MappingOptions options)
   in Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ListShardMapper'1.Update(PointMapping'1 currentMapping, PointMappingUpdate update, Guid lockOwnerId, MappingOptions options)
   in Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.BaseShardMapper.SetStatus[TMapping,TUpdate,TStatus](TMapping mapping, TStatus status, Func'2 getStatus, Func'2 createUpdate, Func'5 runUpdate, Guid lockOwnerId, MappingOptions options)
   in Microsoft.Azure.SqlDatabase..ElasticScale.ShardManagement.ListShardMapper'1.MarkMappingOffline(PointMapping'1 mapping, Guid lockOwnerId, MappingOptions options)
   in Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ListShardMap'1.MarkMappingOffline(PointMapping'1 mapping, MappingOptions options)
`

**Comment by marklar423** [comment]
Version 1.3.0 didn't work for me on Azure, but downgrading from 1.3.3 to 1.3.1 did work.

**Comment by nicksolsen** [comment]
Version 1.3.1 worked for me.

**Comment by coldwell** [comment]
I also experienced timeouts on 1.3.3. Downgrading to 1.3.2 worked as expected.

**Comment by brainded** [comment]
Has this been resolved in later builds? I am still on 1.3.2.

**Comment by jaredmoo** [comment]
Sorry, no investigation or fix yet.

**Comment by brainded** [comment]
According to AppInsights the particular culprit is the following stored proc causing 100% of my timeouts: __ShardManagement.spKillSessionsForShardMappingLocal

**Comment by jaredmoo** [comment]
That makes sense. Killing sessions can be slow if you have large transactions that are slow to roll back.

**Comment by brainded** [comment]
Is there something I could do to preemptively guard against that? Something I could potentially call to tell me that its not likely to work?

**Comment by jaredmoo** [comment]
I believe so, SQL has DMV's that you can query to get information about active sessions/transactions/etc.

**Comment by devscalemat** [comment]
Is there any update/advice for this issue?
It tried to upgrade/downgrade client version. I have almost full elastic pool right now (97 dbs) and it would be nice to remove not needed ones since some tenants are no longer using the app.
I'm getting timeouts every time i try to set mapping to offline

**Comment by scottpantall** [comment]
I came across this issue using v2.3.0. I was able to use this method by including the `MappingOptions` parameter. `mapping = ShardMap.MarkMappingOffline(mapping, MappingOptions.None);`.

**Comment by calloncampbell** [comment]
We're also getting this issue. We're using the latest version of the library (2.4.2)

.NET version: 8.0

Nuget package: `Microsoft.Azure.SqlDatabase.ElasticScale.Client` = `2.4.2`

Here is the exception details:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ShardManagementException: Store Error: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.. The error occurred while attempting to perform the underlying storage operation during 'Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreException: Error occurred while performing store operation. See the inner SqlException for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader()
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.SqlStoreTransactionScope.<>c__DisplayClass11_0.<ExecuteOperation>b__0()
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.SqlUtils.WithSqlExceptionHandling[TResult](Func`1 operation)
ClientConnectionId:d0de47bb-4e10-43ea-906f-5c56dac1c4ae
Error Number:-2,State:0,Class:11
   --- End of inner exception stack trace ---
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.SqlUtils.WithSqlExceptionHandling[TResult](Func`1 operation)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.SqlStoreTransactionScope.ExecuteOperation(String operationName, XElement operationData)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.UpdateMappingOperation.<KillConnectionsOnSourceShard>b__33_0()
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.SqlUtils.WithSqlExceptionHandling(Action operation)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.UpdateMappingOperation.KillConnectionsOnSourceShard()
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.UpdateMappingOperation.DoLocalSourceExecute(IStoreTransactionScope ts)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperation.DoLocalSource()
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperation.<Do>b__32_0()
   at Microsoft.Azure.SqlDatabase.ElasticScale.TransientFaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperation.Do()' operation on shard 'UpdatePointMappingMarkOffline'. See the inner StoreException for details.
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.StoreOperation.Do()
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.BaseShardMapper.Update[TMapping,TUpdate,TStatus](TMapping currentMapping, TUpdate update, Func`4 constructMapping, Func`2 statusAsInt, Func`2 intAsStatus, Guid lockOwnerId, MappingOptions options)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ListShardMapper`1.Update(PointMapping`1 currentMapping, PointMappingUpdate update, Guid lockOwnerId, MappingOptions options)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ListShardMap`1.UpdateMapping(PointMapping`1 currentMapping, PointMappingUpdate update, MappingLockToken mappingLockToken)
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.ListShardMap`1.UpdateMapping(PointMapping`1 currentMapping, PointMappingUpdate update)
   at ElasticShardSqlUtil.Services.ShardManagement.DeleteShardAction(ShardOptions options) in /home/runner/work/dni/dni/src/ElasticShardSqlUtil/DNI.ElasticSqlTool/Services/ShardManagement.cs:line 359
   at ElasticShardSqlUtil.Program.DeleteShardCommand(ShardOptions options, IHost host) in /home/runner/work/dni/dni/src/ElasticShardSqlUtil/DNI.ElasticSqlTool/Program.cs:line 307
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.CommandLine.NamingConventionBinder.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Hosting.HostingExtensions.<>c__DisplayClass1_0.<<UseHost>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
PS E:\program files\Telmetrics\ElasticShardSqlUtil>

```

I'm happy to share additional code if needed.
