### ISSUE TITLE
TFH resources file is not built correctly

### ISSUE THREAD

**Issue by SilviaDoomra** [Azure/elastic-db-tools#90]
The resources file in EDCL's internal copy of Transient Fault Handling is not built correctly. This should not be visible to customers today, since it only contains exception messages for TFH (which should never happen) but it may give us weird errors in the future.

```
    /// <summary>
    /// Resources files are extremely fragile. Verify that the TFH resources are built correctly.
    /// </summary>
    [TestMethod()]
    [TestCategory("ExcludeFromGatedCheckin")]
    public void VerifyTransientFaultHandlingResourcesLoaded()
    {
        AssertExtensions.AssertThrows<ArgumentException>(() =>
            new Microsoft.Azure.SqlDatabase.ElasticScale.Common.TransientFaultHandling.Implementation.Incremental(
                -1, TimeSpan.Zero, TimeSpan.Zero));
    }
```

Result Message: 
Test method Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.UnitTests.ScenarioTests.VerifyTransientFaultHandlingResourcesLoaded threw exception: 
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.Properties.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.SqlDatabase.ElasticScale.Client" at compile time, or that all the satellite assemblies required are loadable and fully signed.
Result StackTrace: 
at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.Properties.Resources.get_ArgumentCannotBeNegative() in d:\elastic_scale_main_1\Src\Client\ElasticScale.Common\Properties\Resources.Designer.cs:line 77
   at Microsoft.Azure.SqlDatabase.ElasticScale.Common.TransientFaultHandling.Implementation.Guard.ArgumentNotNegativeValue(Int32 argumentValue, String argumentName) in d:\elastic_scale_main_1\Src\Client\ElasticScale.Common\TransientFaultHandling\Implementation\Guard.cs:line 58
   at Microsoft.Azure.SqlDatabase.ElasticScale.Common.TransientFaultHandling.Implementation.Incremental..ctor(String name, Int32 retryCount, TimeSpan initialInterval, TimeSpan increment, Boolean firstFastRetry) in d:\elastic_scale_main_1\Src\Client\ElasticScale.Common\TransientFaultHandling\Implementation\Incremental.cs:line 58
   at Microsoft.Azure.SqlDatabase.ElasticScale.Common.TransientFaultHandling.Implementation.Incremental..ctor(String name, Int32 retryCount, TimeSpan initialInterval, TimeSpan increment) in d:\elastic_scale_main_1\Src\Client\ElasticScale.Common\TransientFaultHandling\Implementation\Incremental.cs:line 42
   at Microsoft.Azure.SqlDatabase.ElasticScale.Common.TransientFaultHandling.Implementation.Incremental..ctor(Int32 retryCount, TimeSpan initialInterval, TimeSpan increment) in d:\elastic_scale_main_1\Src\Client\ElasticScale.Common\TransientFaultHandling\Implementation\Incremental.cs:line 30
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.UnitTests.ScenarioTests.<VerifyTransientFaultHandlingResourcesLoaded>b__f() in d:\elastic_scale_main_1\Src\ShardMapManager\ShardMapManagerUnitTests\ScenarioTests.cs:line 894
   at Microsoft.Azure.SqlDatabase.ElasticScale.Test.Common.AssertExtensions.AssertThrows[TException](Action action) in d:\elastic_scale_main_1\Src\Common\ElasticScale.Test.Common\AssertExtensions.cs:line 25
   at Microsoft.Azure.SqlDatabase.ElasticScale.ShardManagement.UnitTests.ScenarioTests.VerifyTransientFaultHandlingResourcesLoaded() in d:\elastic_scale_main_1\Src\ShardMapManager\ShardMapManagerUnitTests\ScenarioTests.cs:line 893

**Comment by jaredmoo** [comment]
Minor issue that is not visible to users. Closing
